#+title: tra: Transducers in Common Lisp

This is an implementation of SRFI-171 (Transducers) in Common Lisp. Originally
inspired by Clojure and adapted to Scheme, Transducers are an excellent way to
think about - and efficiently operate on - collections or streams of data. In
the simplest case the data source could be a List, but files can also be treated
so and have their contents operated over using all the usual functions like =map=,
=filter=, =fold=, and others.

Transducers make dealing with data an efficient joy!

* Table of Contents :toc_3_gh:
- [[#installation][Installation]]
- [[#usage][Usage]]
  - [[#differences-with-srfi-171][Differences with SRFI-171]]
    - [[#scheme][Scheme]]
    - [[#additional-functions][Additional Functions]]

* Installation

* Usage

** Differences with SRFI-171

*** Scheme

Due to differences in how functions are called in Common Lisp and Scheme, all
reducers (like =rcons=) have been made functions that must be called once to get
access to their inner reducing lambda. In practice this means you must do:

#+begin_src lisp
(list-transduce (tmap #'1+) (rcons) '(1 2 3))
#+end_src

instead of:

#+begin_src lisp
(list-transduce (tmap 1+) rcons '(1 2 3))
#+end_src

Notice also that higher-order functions (like =1+=) must be quoted in Common Lisp,
but not so in Scheme.

*** Additional Functions

A few extra functions have been added here that represent idioms common in other
languages, but that are nonetheless missing from the original SRFI-171
specification.
